services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-automikan
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /path/to/qbittorrent/appdata:/config
      - /path/to/data/downloads:/data/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - automikan
    restart: unless-stopped

  automikan:
    build:
      context: ..
      dockerfile: docker/Dockerfile-server
    image: 6uau9/automikan:latest
    container_name: automikan
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/data:/data # /data/poster; /data/downloads; /data/bungumi
      - /path/to/torrents:/torrents
      - /path/to/automikan:/automikan
      # - /path/to/downloads:/downloads
    ports:
      - 8236:8236
    networks:
      - automikan
    restart: unless-stopped

networks:
  automikan:
    name: automikan
    driver: bridge