FROM python:3.10-slim

RUN apt-get update
RUN apt-get install -y tini gosu
RUN pip install --upgrade pip

RUN mkdir /torrent
RUN mkdir /data
RUN mkdir /data/bangumi
RUN mkdir /data/downloads
RUN mkdir /data/poster
RUN mkdir /automikan

WORKDIR /server
COPY ./server/requirements.txt /server/requirements.txt
RUN pip install --no-cache-dir -r /server/requirements.txt
COPY docker/entrypoint-server.sh /entrypoint.sh
COPY ./server/ /server

EXPOSE 8236
VOLUME [ "/torrent" , "/data", "/automikan" ]

ENTRYPOINT ["tini", "-g", "--", "/entrypoint.sh"]