FROM python:3.10-slim

RUN apt-get update
RUN apt-get install -y tini gosu
RUN pip install --upgrade pip

COPY ./server/ /server
COPY docker/entrypoint-server.sh /entrypoint.sh
WORKDIR /server
RUN pip install --no-cache-dir -r /server/requirements.txt

EXPOSE 8236
VOLUME [ "/torrent" , "/bangumi", "/automikan" ]

ENTRYPOINT ["tini", "-g", "--", "/entrypoint.sh"]